version: "3"
networks:
    jenkins_cicd:
volumes:
    jenkins_home:
        driver: local
    codescene:
        driver: local
    codescene_code_coverage_data:
        driver: local
    sonarqube_logs:
        driver: local
    sonarqube_conf:
        driver: local
    sonarqube_data:
        driver: local
    sonarqube_extension:
        driver: local
    postgresql_conf:
        driver: local
    postgresql_logs:
        driver: local
    postgresql_lib:
        driver: local
    postgresql_data:
        driver: local

services:
    extensure_jenkins:
        user: root
        build: jenkins/.
        container_name: extensure_jenkins
        ports:
            - "${EXTENSURE_JENKINS_PORT}:8080"
            - "${EXTENSURE_JENKINS_SLAVE_PORT}:5000"
        networks:
            - jenkins_cicd
        environment:
            - "JENKINS_USER=${EXTENSURE_JENKINS_USER}"
            - "JENKINS_PASS=${EXTENSURE_JENKINS_PASSWORD}"
        volumes:
            - jenkins_home:/var/jenkins_home
    extensure_codescene:
        build: codescene/.
        container_name: extensure_codescene
        ports:
            - "${EXTENSURE_CODESCENE_PORT}:3003"
        networks:
            - jenkins_cicd
        volumes:
            - codescene:/codescene
            - codescene_code_coverage_data:/code-coverage-data
    extensure_sonarqube:
        build: sonarqube/.
        container_name: extensure_sonarqube
        ports:
            - "${EXTENSURE_SONAR_PORT}:9000"
        networks:
            - jenkins_cicd
        environment:
            - "sonar.jdbc.url=jdbc:${EXTENSURE_SONAR_POSTGRES_URL}"
            - "sonar.jdbc.username=${EXTENSURE_SONAR_POSTGRES_USER}"
            - "sonar.jdbc.password=${EXTENSURE_SONAR_POSTGRES_PASSWORD}"
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extension:/opt/sonarqube/extensions
    extensure_postgresdb:
        build: postgres/.
        container_name: extensure_postgresdb
        ports:
            - "${EXTENSURE_SONAR_POSTGRES_PORT}:5432"
        networks:
            - jenkins_cicd
        environment:
            - "POSTGRES_DB=${EXTENSURE_SONAR_POSTGRES_DB}"
            - "POSTGRES_USER=${EXTENSURE_SONAR_POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${EXTENSURE_SONAR_POSTGRES_PASSWORD}"
        volumes:
            - postgresql_conf:/etc/postgresql
            - postgresql_logs:/var/log/postgresql
            - postgresql_lib:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        
